In [1]:
import numpy as np

In [2]:
n1=np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [3]:
n2=np.array((10,20,30,40))
n2

array([10, 20, 30, 40])

In [5]:
n3=np.zeros((3,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
n3.dtype

dtype('float64')

In [7]:
n4=np.ones((2,2))
n4

array([[1., 1.],
       [1., 1.]])

In [15]:
n5=np.full((3,3),10, dtype='complex')
n5

array([[10.+0.j, 10.+0.j, 10.+0.j],
       [10.+0.j, 10.+0.j, 10.+0.j],
       [10.+0.j, 10.+0.j, 10.+0.j]])

In [13]:
n5.dtype

dtype('int32')

In [19]:
n6=np.arange(11,20).reshape(3,3)
n6

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [37]:
#n7=np.random.randint(10,20,5)
#n7=np.random.randint(10,20,(2,2))
n7=np.random.randint(10,20,4).reshape(2,2)
n7

array([[14, 14],
       [19, 14]])